[2022-09-22T08:27:10.620+0000] {processor.py:156} INFO - Started process (PID=1165) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:27:10.621+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:27:10.622+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:27:10.622+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:27:10.821+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:27:10.819+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:27:10.822+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:27:12.107+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 1.902 seconds
[2022-09-22T08:27:42.352+0000] {processor.py:156} INFO - Started process (PID=1184) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:27:42.444+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:27:42.446+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:27:42.445+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:27:42.450+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:27:42.448+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:27:42.457+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:27:44.406+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 2.059 seconds
[2022-09-22T08:28:14.598+0000] {processor.py:156} INFO - Started process (PID=1204) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:28:14.656+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:28:14.658+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:28:14.657+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:28:14.701+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:28:14.700+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:28:14.702+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:28:14.746+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.156 seconds
[2022-09-22T08:28:44.957+0000] {processor.py:156} INFO - Started process (PID=1229) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:28:45.016+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:28:45.017+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:28:45.016+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:28:45.022+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:28:45.020+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:28:45.023+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:28:45.085+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.134 seconds
[2022-09-22T08:29:15.260+0000] {processor.py:156} INFO - Started process (PID=1251) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:29:15.261+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:29:15.261+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:29:15.261+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:29:15.265+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:29:15.263+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:29:15.265+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:29:15.317+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.061 seconds
[2022-09-22T08:29:45.435+0000] {processor.py:156} INFO - Started process (PID=1271) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:29:45.436+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:29:45.437+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:29:45.436+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:29:45.439+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:29:45.438+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:29:45.440+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:29:45.509+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.078 seconds
[2022-09-22T08:30:15.671+0000] {processor.py:156} INFO - Started process (PID=1299) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:30:15.672+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:30:15.673+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:30:15.673+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:30:15.677+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:30:15.675+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:30:15.677+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:30:15.741+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.074 seconds
[2022-09-22T08:30:45.887+0000] {processor.py:156} INFO - Started process (PID=1319) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:30:45.907+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:30:45.907+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:30:45.907+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:30:45.910+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:30:45.909+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:30:45.911+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:30:45.958+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.075 seconds
[2022-09-22T08:31:16.140+0000] {processor.py:156} INFO - Started process (PID=1346) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:31:16.162+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:31:16.164+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:31:16.163+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:31:16.168+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:31:16.166+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:31:16.169+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:31:16.233+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.097 seconds
[2022-09-22T08:31:46.371+0000] {processor.py:156} INFO - Started process (PID=1365) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:31:46.390+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:31:46.391+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:31:46.390+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:31:46.415+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:31:46.414+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:31:46.416+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:31:46.490+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.122 seconds
[2022-09-22T08:32:16.596+0000] {processor.py:156} INFO - Started process (PID=1385) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:32:16.602+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:32:16.603+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:32:16.603+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:32:16.607+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:32:16.605+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:32:16.608+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:32:17.152+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.563 seconds
[2022-09-22T08:40:32.551+0000] {processor.py:156} INFO - Started process (PID=49) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:40:32.632+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:40:32.633+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:40:32.633+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:40:32.637+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:40:32.635+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:40:32.637+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:40:32.767+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.226 seconds
[2022-09-22T08:41:03.186+0000] {processor.py:156} INFO - Started process (PID=69) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:41:03.205+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:41:03.206+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:41:03.206+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:41:03.210+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:41:03.209+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:41:03.211+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:41:03.270+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.090 seconds
[2022-09-22T08:41:33.768+0000] {processor.py:156} INFO - Started process (PID=96) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:41:33.864+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:41:33.866+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:41:33.865+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:41:35.158+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:41:34.306+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:41:35.159+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:41:35.587+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 1.823 seconds
[2022-09-22T08:42:05.799+0000] {processor.py:156} INFO - Started process (PID=116) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:42:05.813+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:42:05.814+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:42:05.814+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:42:05.817+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:42:05.816+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:42:05.818+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:42:05.974+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.180 seconds
[2022-09-22T08:42:36.377+0000] {processor.py:156} INFO - Started process (PID=142) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:42:36.395+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:42:36.396+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:42:36.395+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:42:36.420+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:42:36.397+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:42:36.421+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:42:36.618+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.287 seconds
[2022-09-22T08:43:07.308+0000] {processor.py:156} INFO - Started process (PID=163) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:43:07.310+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:43:07.311+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:43:07.310+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:43:07.313+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:43:07.312+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:43:07.314+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:43:07.350+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.045 seconds
[2022-09-22T08:43:37.458+0000] {processor.py:156} INFO - Started process (PID=183) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:43:37.459+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:43:37.460+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:43:37.460+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:43:37.463+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:43:37.462+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:43:37.463+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:43:37.495+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.041 seconds
[2022-09-22T08:44:07.657+0000] {processor.py:156} INFO - Started process (PID=212) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:44:07.663+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:44:07.664+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:44:07.664+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:44:07.669+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:44:07.666+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:44:07.669+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:44:07.730+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.079 seconds
[2022-09-22T08:44:37.815+0000] {processor.py:156} INFO - Started process (PID=232) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:44:37.816+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:44:37.817+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:44:37.817+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:44:37.819+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:44:37.818+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:44:37.819+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:44:37.854+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.042 seconds
[2022-09-22T08:45:07.968+0000] {processor.py:156} INFO - Started process (PID=261) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:45:07.981+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:45:07.982+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:45:07.981+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:45:07.984+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:45:07.983+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:45:07.984+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:45:08.013+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.049 seconds
[2022-09-22T08:45:38.150+0000] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:45:38.151+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:45:38.151+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:45:38.151+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:45:38.154+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:45:38.153+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:45:38.154+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:45:38.191+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.045 seconds
[2022-09-22T08:46:08.306+0000] {processor.py:156} INFO - Started process (PID=304) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:46:08.307+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:46:08.308+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:46:08.308+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:46:08.310+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:46:08.309+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:46:08.311+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:46:08.348+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.045 seconds
[2022-09-22T08:46:38.505+0000] {processor.py:156} INFO - Started process (PID=323) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:46:38.524+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:46:38.525+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:46:38.525+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:46:38.533+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:46:38.532+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:46:38.534+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:46:38.591+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.091 seconds
[2022-09-22T08:47:08.693+0000] {processor.py:156} INFO - Started process (PID=352) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:47:08.694+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:47:08.695+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:47:08.695+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:47:08.698+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:47:08.697+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:47:08.698+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:47:08.816+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.126 seconds
[2022-09-22T08:47:38.913+0000] {processor.py:156} INFO - Started process (PID=372) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:47:38.931+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:47:38.933+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:47:38.932+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:47:38.935+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:47:38.934+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:47:38.936+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:47:39.048+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.138 seconds
[2022-09-22T08:48:09.125+0000] {processor.py:156} INFO - Started process (PID=401) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:48:09.126+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:48:09.127+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:48:09.127+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:48:09.130+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:48:09.128+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:48:09.130+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:48:09.162+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.041 seconds
[2022-09-22T08:48:39.306+0000] {processor.py:156} INFO - Started process (PID=420) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:48:39.307+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:48:39.308+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:48:39.308+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:48:39.311+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:48:39.310+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:48:39.311+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:48:39.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.044 seconds
[2022-09-22T08:49:09.480+0000] {processor.py:156} INFO - Started process (PID=439) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:49:09.482+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:49:09.482+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:49:09.482+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:49:09.485+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:49:09.484+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:49:09.485+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:49:09.530+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.052 seconds
[2022-09-22T08:49:39.684+0000] {processor.py:156} INFO - Started process (PID=467) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:49:39.736+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:49:39.737+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:49:39.737+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:49:39.740+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:49:39.739+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:49:39.741+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:49:39.792+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.114 seconds
[2022-09-22T08:50:09.840+0000] {processor.py:156} INFO - Started process (PID=487) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:50:09.841+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:50:09.842+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:50:09.842+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:50:09.844+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:50:09.843+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:50:09.845+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:50:09.874+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.038 seconds
[2022-09-22T08:50:40.024+0000] {processor.py:156} INFO - Started process (PID=515) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:50:40.039+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:50:40.041+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:50:40.040+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:50:40.045+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:50:40.043+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:50:40.046+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:50:40.245+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.236 seconds
[2022-09-22T08:51:10.497+0000] {processor.py:156} INFO - Started process (PID=534) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:51:10.499+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:51:10.501+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:51:10.500+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:51:10.516+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:51:10.515+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:51:10.517+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:51:10.643+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.151 seconds
[2022-09-22T08:51:40.669+0000] {processor.py:156} INFO - Started process (PID=553) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:51:40.669+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:51:40.670+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:51:40.670+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:51:40.673+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:51:40.672+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:51:40.674+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:51:40.742+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.078 seconds
[2022-09-22T08:52:10.862+0000] {processor.py:156} INFO - Started process (PID=582) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:52:10.886+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:52:10.887+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:52:10.887+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:52:10.891+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:52:10.889+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:52:10.891+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:52:10.942+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.085 seconds
[2022-09-22T08:52:41.077+0000] {processor.py:156} INFO - Started process (PID=601) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:52:41.078+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:52:41.079+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:52:41.079+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:52:41.082+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:52:41.081+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:52:41.082+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:52:41.118+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.045 seconds
[2022-09-22T08:53:11.270+0000] {processor.py:156} INFO - Started process (PID=630) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:53:11.271+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:53:11.272+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:53:11.272+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:53:11.275+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:53:11.274+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:53:11.275+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:53:11.326+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.060 seconds
[2022-09-22T08:53:41.463+0000] {processor.py:156} INFO - Started process (PID=649) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:53:41.476+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:53:41.477+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:53:41.477+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:53:41.482+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:53:41.479+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:53:41.482+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:53:41.550+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.091 seconds
[2022-09-22T08:54:11.629+0000] {processor.py:156} INFO - Started process (PID=676) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:54:11.630+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:54:11.631+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:54:11.631+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:54:11.634+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:54:11.633+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:54:11.634+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:54:11.672+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.047 seconds
[2022-09-22T08:54:41.798+0000] {processor.py:156} INFO - Started process (PID=695) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:54:41.815+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:54:41.816+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:54:41.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:54:41.821+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:54:41.819+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:54:41.821+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:54:41.860+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.068 seconds
[2022-09-22T08:55:12.054+0000] {processor.py:156} INFO - Started process (PID=722) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:55:12.055+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:55:12.056+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:55:12.056+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:55:12.064+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:55:12.063+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:55:12.065+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:55:12.225+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.185 seconds
[2022-09-22T08:55:42.386+0000] {processor.py:156} INFO - Started process (PID=741) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:55:42.399+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:55:42.400+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:55:42.400+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:55:42.404+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:55:42.402+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 58
    CARS_table, TRAJECTORIES_tables = extractor.extract_data('../data/20181024_d1_0830_0900.csv', return_json=True)
             ^
SyntaxError: invalid syntax
[2022-09-22T08:55:42.404+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:55:42.437+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.055 seconds
[2022-09-22T08:56:03.521+0000] {processor.py:156} INFO - Started process (PID=759) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:56:03.522+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:56:03.524+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:03.523+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:03.537+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:03.535+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 66
    COPY CARS(emp_id,firstcd_name,last_name,dob,city)
            ^
SyntaxError: invalid syntax
[2022-09-22T08:56:03.537+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:03.669+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.153 seconds
[2022-09-22T08:56:29.701+0000] {processor.py:156} INFO - Started process (PID=778) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:56:29.703+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:56:29.704+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:29.704+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:31.438+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:31.436+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 11, in <module>
    from data_extract import DataExtractor
ModuleNotFoundError: No module named 'data_extract'
[2022-09-22T08:56:31.440+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:31.496+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 1.804 seconds
[2022-09-22T08:56:45.619+0000] {processor.py:156} INFO - Started process (PID=788) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:56:45.620+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:56:45.621+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:45.621+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:45.747+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:45.746+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 11, in <module>
    from data_extract import DataExtractor
ModuleNotFoundError: No module named 'data_extract'
[2022-09-22T08:56:45.748+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:45.826+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.211 seconds
[2022-09-22T08:56:57.932+0000] {processor.py:156} INFO - Started process (PID=798) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:56:57.933+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:56:57.934+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:57.934+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:57.941+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:56:57.939+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/load_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/load_data.py", line 9, in <module>
    from data_extract import DataExtractor
ModuleNotFoundError: No module named 'data_extract'
[2022-09-22T08:56:57.942+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:56:58.034+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.107 seconds
[2022-09-22T08:57:07.123+0000] {processor.py:156} INFO - Started process (PID=808) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:57:07.141+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:57:07.143+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:57:07.143+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:57:09.584+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:57:09.643+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 2.525 seconds
[2022-09-22T08:57:39.843+0000] {processor.py:156} INFO - Started process (PID=828) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:57:39.853+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:57:39.854+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:57:39.854+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:57:40.368+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:57:40.398+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.561 seconds
[2022-09-22T08:58:10.489+0000] {processor.py:156} INFO - Started process (PID=857) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:58:10.492+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:58:10.494+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:58:10.494+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:58:11.167+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:58:11.202+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.719 seconds
[2022-09-22T08:58:41.447+0000] {processor.py:156} INFO - Started process (PID=877) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:58:41.448+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:58:41.455+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:58:41.449+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:58:42.420+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:58:42.498+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 1.060 seconds
[2022-09-22T08:59:12.593+0000] {processor.py:156} INFO - Started process (PID=907) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:59:12.594+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:59:12.595+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:59:12.595+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:59:13.094+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:59:13.119+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.530 seconds
[2022-09-22T08:59:43.284+0000] {processor.py:156} INFO - Started process (PID=927) to work on /opt/airflow/dags/load_data.py
[2022-09-22T08:59:43.285+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T08:59:43.286+0000] {logging_mixin.py:117} INFO - [2022-09-22T08:59:43.286+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T08:59:43.807+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T08:59:43.835+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.554 seconds
[2022-09-22T09:00:13.988+0000] {processor.py:156} INFO - Started process (PID=956) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:00:13.994+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:00:13.995+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:00:13.995+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:00:14.595+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:00:14.627+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.642 seconds
[2022-09-22T09:00:44.834+0000] {processor.py:156} INFO - Started process (PID=976) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:00:44.835+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:00:44.836+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:00:44.836+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:00:45.401+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:00:45.451+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.622 seconds
[2022-09-22T09:01:15.649+0000] {processor.py:156} INFO - Started process (PID=1002) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:01:15.689+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:01:15.690+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:01:15.690+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:01:16.561+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:01:16.592+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.953 seconds
[2022-09-22T09:01:46.811+0000] {processor.py:156} INFO - Started process (PID=1025) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:01:46.812+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:01:46.812+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:01:46.812+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:01:47.338+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:01:47.377+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.570 seconds
[2022-09-22T09:02:17.569+0000] {processor.py:156} INFO - Started process (PID=1045) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:02:17.570+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:02:17.571+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:02:17.571+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:02:18.061+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:02:18.082+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.517 seconds
[2022-09-22T09:02:48.170+0000] {processor.py:156} INFO - Started process (PID=1075) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:02:48.173+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:02:48.174+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:02:48.174+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:02:48.942+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:02:48.985+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.820 seconds
[2022-09-22T09:03:19.204+0000] {processor.py:156} INFO - Started process (PID=1095) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:03:19.205+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:03:19.206+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:03:19.206+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:03:19.667+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:03:19.688+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.488 seconds
[2022-09-22T09:03:49.863+0000] {processor.py:156} INFO - Started process (PID=1126) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:03:49.864+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:03:49.865+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:03:49.864+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:03:50.313+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:03:50.334+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.475 seconds
[2022-09-22T09:04:20.533+0000] {processor.py:156} INFO - Started process (PID=1146) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:04:20.534+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:04:20.535+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:04:20.535+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:04:21.091+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:04:21.112+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.584 seconds
[2022-09-22T09:04:51.194+0000] {processor.py:156} INFO - Started process (PID=1177) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:04:51.195+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:04:51.195+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:04:51.195+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:04:51.625+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:04:51.647+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.457 seconds
[2022-09-22T09:05:21.812+0000] {processor.py:156} INFO - Started process (PID=1197) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:05:21.834+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:05:21.835+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:05:21.834+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:05:22.391+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:05:22.414+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.607 seconds
[2022-09-22T09:05:52.627+0000] {processor.py:156} INFO - Started process (PID=1225) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:05:52.655+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:05:52.657+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:05:52.656+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:05:53.073+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:05:53.097+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.473 seconds
[2022-09-22T09:06:23.130+0000] {processor.py:156} INFO - Started process (PID=1245) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:06:23.131+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:06:23.132+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:06:23.132+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:06:23.570+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:06:23.590+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.463 seconds
[2022-09-22T09:06:53.769+0000] {processor.py:156} INFO - Started process (PID=1274) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:06:53.770+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:06:53.771+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:06:53.771+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:06:54.210+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:06:54.231+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.466 seconds
[2022-09-22T09:07:24.406+0000] {processor.py:156} INFO - Started process (PID=1295) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:07:24.406+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:07:24.407+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:07:24.407+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:24.858+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:24.881+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.480 seconds
[2022-09-22T09:07:55.075+0000] {processor.py:156} INFO - Started process (PID=1325) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:07:55.102+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:07:55.103+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:07:55.103+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:56.012+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:56.046+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.976 seconds
[2022-09-22T09:07:58.125+0000] {processor.py:156} INFO - Started process (PID=1327) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:07:58.127+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:07:58.128+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:07:58.127+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:58.870+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:07:58.905+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.792 seconds
[2022-09-22T09:08:29.083+0000] {processor.py:156} INFO - Started process (PID=1346) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:08:29.084+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:08:29.085+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:08:29.085+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:08:29.547+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:08:29.569+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.488 seconds
[2022-09-22T09:08:59.753+0000] {processor.py:156} INFO - Started process (PID=1376) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:08:59.754+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:08:59.755+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:08:59.754+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:09:00.373+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:09:00.401+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.651 seconds
[2022-09-22T09:09:30.580+0000] {processor.py:156} INFO - Started process (PID=1395) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:09:30.595+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:09:30.596+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:09:30.596+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:09:31.312+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:09:31.349+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.774 seconds
[2022-09-22T09:10:01.542+0000] {processor.py:156} INFO - Started process (PID=1424) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:10:01.543+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:10:01.543+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:10:01.543+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:10:01.969+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:10:01.989+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.450 seconds
[2022-09-22T09:10:32.166+0000] {processor.py:156} INFO - Started process (PID=1445) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:10:32.170+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:10:32.171+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:10:32.171+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:10:32.822+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:10:32.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.696 seconds
[2022-09-22T09:11:03.079+0000] {processor.py:156} INFO - Started process (PID=1473) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:11:03.080+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:11:03.081+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:11:03.080+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:11:03.515+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:11:03.534+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.460 seconds
[2022-09-22T09:11:33.692+0000] {processor.py:156} INFO - Started process (PID=1493) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:11:33.693+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:11:33.694+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:11:33.694+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:11:34.237+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:11:34.271+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.582 seconds
[2022-09-22T09:12:04.439+0000] {processor.py:156} INFO - Started process (PID=1523) to work on /opt/airflow/dags/load_data.py
[2022-09-22T09:12:04.440+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/load_data.py for tasks to queue
[2022-09-22T09:12:04.441+0000] {logging_mixin.py:117} INFO - [2022-09-22T09:12:04.441+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/load_data.py
[2022-09-22T09:12:04.977+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/load_data.py
[2022-09-22T09:12:05.002+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/load_data.py took 0.566 seconds
