[2022-09-22T23:30:25.192+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T23:30:15.246659+00:00 [queued]>
[2022-09-22T23:30:25.225+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: loading_data.insert_data manual__2022-09-22T23:30:15.246659+00:00 [queued]>
[2022-09-22T23:30:25.226+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T23:30:25.226+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-09-22T23:30:25.226+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-09-22T23:30:25.282+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): insert_data> on 2022-09-22 23:30:15.246659+00:00
[2022-09-22T23:30:25.289+0000] {standard_task_runner.py:54} INFO - Started process 22033 to run task
[2022-09-22T23:30:25.301+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'loading_data', 'insert_data', 'manual__2022-09-22T23:30:15.246659+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/load_data.py', '--cfg-path', '/tmp/tmphwzo7xx5']
[2022-09-22T23:30:25.302+0000] {standard_task_runner.py:83} INFO - Job 72: Subtask insert_data
[2022-09-22T23:30:25.305+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/***/dags/load_data.py
[2022-09-22T23:30:28.804+0000] {task_command.py:384} INFO - Running <TaskInstance: loading_data.insert_data manual__2022-09-22T23:30:15.246659+00:00 [running]> on host c1ab2cb1bbac
[2022-09-22T23:30:29.566+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=loading_data
AIRFLOW_CTX_TASK_ID=insert_data
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T23:30:15.246659+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-22T23:30:15.246659+00:00
[2022-09-22T23:30:29.721+0000] {logging_mixin.py:117} INFO - Failed  ---- [Errno 2] No such file or directory: '../data/trajectories_table.csv'
[2022-09-22T23:30:29.725+0000] {python.py:177} INFO - Done. Returned value was: None
[2022-09-22T23:30:29.809+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=loading_data, task_id=insert_data, execution_date=20220922T233015, start_date=20220922T233025, end_date=20220922T233029
[2022-09-22T23:30:30.379+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2022-09-22T23:30:30.491+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
